#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function setup() {
  console.log('🚀 NOVA AI Chatbot Setup');
  console.log('========================\n');
  
  const envPath = path.join(__dirname, '.env');
  
  // Check if .env already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y' && overwrite.toLowerCase() !== 'yes') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }
  
  console.log('\n📝 Let\'s configure your API keys:');
  console.log('(Press Enter to skip optional fields)\n');
  
  const geminiKey = await question('🔑 Gemini API Key (required for chat): ');
  const weatherKey = await question('🌤️  Weather API Key (optional, for weather queries): ');
  const googleClientId = await question('🔐 Google OAuth Client ID (optional, uses default if empty): ');
  const port = await question('🌐 Server Port (default: 3000): ');
  
  // Create .env content
  let envContent = `# Environment Variables for NOVA AI Chatbot
# Generated by setup script

# Gemini API Key - Get from https://makersuite.google.com/app/apikey
GEMINI_API_KEY=${geminiKey || 'your_gemini_api_key_here'}

# Weather API Key - Get from https://openweathermap.org/api
WEATHER_API_KEY=${weatherKey || 'your_weather_api_key_here'}

# Server Configuration
PORT=${port || '3000'}

# Google OAuth Configuration (Optional)
GOOGLE_CLIENT_ID=${googleClientId || '58005689001-8gbri4rvbc2ho0snaolahd29ruqpm1e0.apps.googleusercontent.com'}
`;
  
  // Write .env file
  fs.writeFileSync(envPath, envContent);
  
  console.log('\n✅ Setup complete!');
  console.log('\n📋 Next steps:');
  console.log('1. Run: npm start');
  console.log('2. Open: http://localhost:' + (port || '3000'));
  console.log('\n💡 Tips:');
  console.log('- Get Gemini API key: https://makersuite.google.com/app/apikey');
  console.log('- Get Weather API key: https://openweathermap.org/api');
  console.log('- Admin login: admin / admin123');
  
  if (!geminiKey) {
    console.log('\n⚠️  Warning: No Gemini API key provided. Chat functionality will be limited.');
  }
  
  rl.close();
}

setup().catch(console.error);
